// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eubbhwvkgztkagydfapv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1YmJod3ZrZ3p0a2FneWRmYXB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MDg3OTIsImV4cCI6MjA2NjA4NDc5Mn0.rQRaD7Ib0B8eTOsNXN7-UzX2I9ASMnBvIyzPmvO9ZHY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);